Feature: connecting RVDC services

  As an Accor Network Engineer,
  I ...
  in order to ...



Scenario: where an Accor Network Engineer is connecting a RVDC to the Accor corporate infrastructure
  Given one "Accor Network Engineer"
  When ...
  Then ...
