Feature: enforcing compliance for RVDC services

  As an Accor Compliance Engineer,
  I ...
  in order to ...



Scenario: where an Accor Compliance Engineer is extending corporate compliance controls to a RVDC
  Given one "Accor Compliance Engineer"
  When ...
  Then ...
