Feature: continuously optimising RVDC costs

  As an Accor FinOps Engineer,
  I ...
  in order to ...



Scenario: where an Accor FinOps Engineer is extracting costs and usage reports from RVDC
  Given one "Accor FinOps Engineer"
  When ...
  Then ...
