Feature: connecting RVDC to identity management

  As an Accor Identity Engineer,
  I ...
  in order to ...



Scenario: where an Accor Identity Engineer is extending the corporate directory to a RVDC
  Given one "Accor Identity Engineer"
  When ...
  Then ...
