Feature: securing RVDC services

  As an Accor Security Engineer,
  I ...
  in order to ...



Scenario: where an Accor Security Engineer is extending corporate cyber-security controls to a RVDC
  Given one "Accor Security Engineer"
  When ...
  Then ...
